apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springbootdockerexample
  name: springbootdockerexample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springbootdockerexample
    spec:
      containers:
      - image: naresh240/springbootdockerexample
        name: springbootdockerexample
        ports:
        - name: springbootdockerexample
          containerPort: 8888
   
---     
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springbootdockerexample
  name: springbootdockerexample
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30000
  selector:
    name: springbootdockerexample
